import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ThemeWrapper from "@/theme/ThemeWrapper";
import { AppBar, Toolbar, Typography, Button, Container } from "@mui/material";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} style={{ minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <ThemeWrapper>
          {/* AppBar */}
          <AppBar position="static">
            <Toolbar>
              <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                MyApp
              </Typography>
              <Button color="inherit" component={Link} href="/">
                Home
              </Button>
              <Button color="inherit" component={Link} href="/about">
                About
              </Button>
              <Button color="inherit" component={Link} href="/contact">
                Contact
              </Button>
            </Toolbar>
          </AppBar>

          {/* Main Content */}
          <Container component="main" sx={{ flexGrow: 1, paddingY: 5 }}>
            {children}
          </Container>

          {/* Sticky Footer */}
          <footer style={{ padding: "20px", backgroundColor: "#f1f1f1", textAlign: "center", marginTop: "auto" }}>
            <Typography variant="body2" color="textSecondary">
              © {new Date().getFullYear()} MyApp. All rights reserved.
            </Typography>
          </footer>
        </ThemeWrapper>
      </body>
    </html>
  );
}
