//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoDokas.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoDokas.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes esame aistringi kurti įrankius, kurie įgalina asmenis ir įmones pasiekti savo tikslus. Mūsų misija - teikti intuityvius ir galingus sprendimus, kurie daro poveikį jūsų kasdieniam gyvenimui..
        /// </summary>
        public static string AboutSectionText {
            get {
                return ResourceManager.GetString("AboutSectionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apie projektą 🤠.
        /// </summary>
        public static string AboutSectionTitle {
            get {
                return ResourceManager.GetString("AboutSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papildoma Informacija.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresas.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresas negali viršyti 300 simbolių.
        /// </summary>
        public static string AddressMaxLength {
            get {
                return ResourceManager.GetString("AddressMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresas yra privalomas.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sutarties sudarymo metu.
        /// </summary>
        public static string AtContractFormation {
            get {
                return ResourceManager.GetString("AtContractFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo adresas yra privalomas.
        /// </summary>
        public static string BuyerAddressRequired {
            get {
                return ResourceManager.GetString("BuyerAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo kodas yra privalomas.
        /// </summary>
        public static string BuyerCodeRequired {
            get {
                return ResourceManager.GetString("BuyerCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo El. Paštas.
        /// </summary>
        public static string BuyerEmail {
            get {
                return ResourceManager.GetString("BuyerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo el. paštas yra privalomas.
        /// </summary>
        public static string BuyerEmailRequired {
            get {
                return ResourceManager.GetString("BuyerEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo duomenys.
        /// </summary>
        public static string BuyerInformation {
            get {
                return ResourceManager.GetString("BuyerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo pasirašymo būdas.
        /// </summary>
        public static string BuyerMethod {
            get {
                return ResourceManager.GetString("BuyerMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite, kaip pirkėjas užpildys savo informaciją ir pasirašys sutartį..
        /// </summary>
        public static string BuyerMethodDescription {
            get {
                return ResourceManager.GetString("BuyerMethodDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo vardas yra privalomas.
        /// </summary>
        public static string BuyerNameRequired {
            get {
                return ResourceManager.GetString("BuyerNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjo telefono numeris yra privalomas.
        /// </summary>
        public static string BuyerPhoneRequired {
            get {
                return ResourceManager.GetString("BuyerPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apžvalga.
        /// </summary>
        public static string BuyerReview {
            get {
                return ResourceManager.GetString("BuyerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atšaukti.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Išvalyti.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asmens kodas / įmonės kodas / gimimo data, kai asmens kodas nesuteiktas.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodas turi sudaryti tik skaičiai.
        /// </summary>
        public static string CodeDigitsOnly {
            get {
                return ResourceManager.GetString("CodeDigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodas yra privalomas.
        /// </summary>
        public static string CodeRequired {
            get {
                return ResourceManager.GetString("CodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patvirtinti.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turite sutikti su sąlygomis.
        /// </summary>
        public static string ConsentRequired {
            get {
                return ResourceManager.GetString("ConsentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutarties sudarymo data.
        /// </summary>
        public static string ContractCreationDate {
            get {
                return ResourceManager.GetString("ContractCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Šalis yra privaloma.
        /// </summary>
        public static string CountryRequired {
            get {
                return ResourceManager.GetString("CountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stabdžių sistemos.
        /// </summary>
        public static string Defect_BrakeSystem {
            get {
                return ResourceManager.GetString("Defect_BrakeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dujų išmetimo sistemos.
        /// </summary>
        public static string Defect_ExhaustSystem {
            get {
                return ResourceManager.GetString("Defect_ExhaustSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apšvietimo ir šviesos signalizavimo įtaisų.
        /// </summary>
        public static string Defect_Lighting {
            get {
                return ResourceManager.GetString("Defect_Lighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vairuotojų ir keleivių saugos sistemų.
        /// </summary>
        public static string Defect_SafetySystems {
            get {
                return ResourceManager.GetString("Defect_SafetySystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vairo mechanizmo ir pakabos elementų.
        /// </summary>
        public static string Defect_SteeringSuspension {
            get {
                return ResourceManager.GetString("Defect_SteeringSuspension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės trūkumai.
        /// </summary>
        public static string Defects {
            get {
                return ResourceManager.GetString("Defects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redaguoti.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elektroninio pašto adresas.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neteisingas el. pašto adresas.
        /// </summary>
        public static string EmailInvalid {
            get {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. paštas negali viršyti 100 simbolių.
        /// </summary>
        public static string EmailMaxLength {
            get {
                return ResourceManager.GetString("EmailMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El. paštas yra privalomas.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mėgaukitės žaibiškai greitu veikimu su mūsų pažangia technologija..
        /// </summary>
        public static string Feature1Text {
            get {
                return ResourceManager.GetString("Feature1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greitas veikimas.
        /// </summary>
        public static string Feature1Title {
            get {
                return ResourceManager.GetString("Feature1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes teikiame pirmenybę jūsų saugumui su aukščiausios klasės apsauga ir patikimumu..
        /// </summary>
        public static string Feature2Text {
            get {
                return ResourceManager.GetString("Feature2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saugus ir patikimas.
        /// </summary>
        public static string Feature2Title {
            get {
                return ResourceManager.GetString("Feature2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritaikykite mūsų platformą pagal savo unikalius poreikius su lanksčiais variantais..
        /// </summary>
        public static string Feature3Text {
            get {
                return ResourceManager.GetString("Feature3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pritaikomi įrankiai.
        /// </summary>
        public static string Feature3Title {
            get {
                return ResourceManager.GetString("Feature3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcijos.
        /// </summary>
        public static string FeaturesTitle {
            get {
                return ResourceManager.GetString("FeaturesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eismo ar kiti įvykiai, kuriuose transporto priemonė buvoapgadinta, man žinomi.
        /// </summary>
        public static string HasBeenDamaged {
            get {
                return ResourceManager.GetString("HasBeenDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pildyk sutartį internetu.
        /// </summary>
        public static string HeroSubtitle {
            get {
                return ResourceManager.GetString("HeroSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automobilio pirkimo pardavimo sutartis internetu.
        /// </summary>
        public static string HeroTitle {
            get {
                return ResourceManager.GetString("HeroTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagrindinis.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikavimo numeris (E).
        /// </summary>
        public static string IdentificationNumber {
            get {
                return ResourceManager.GetString("IdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifikavimo numeris yra privalomas.
        /// </summary>
        public static string IdentificationNumberRequired {
            get {
                return ResourceManager.GetString("IdentificationNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to negalioja.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perka/Parduoda Įmonė.
        /// </summary>
        public static string IsCompany {
            get {
                return ResourceManager.GetString("IsCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės privalomoji techninė apžiūra.
        /// </summary>
        public static string IsInspected {
            get {
                return ResourceManager.GetString("IsInspected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gamybinė markė (D.1) ir komercinis pavadinimas (D.3):.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markė yra privaloma.
        /// </summary>
        public static string MakeRequired {
            get {
                return ResourceManager.GetString("MakeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rida.
        /// </summary>
        public static string Millage {
            get {
                return ResourceManager.GetString("Millage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vardas, pavardė arba juridinio asmens pavadinimas.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardas negali viršyti 100 simbolių.
        /// </summary>
        public static string NameMaxLength {
            get {
                return ResourceManager.GetString("NameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vardas yra privalomas.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apie.
        /// </summary>
        public static string NavAbout {
            get {
                return ResourceManager.GetString("NavAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AutoDokas.lt.
        /// </summary>
        public static string NavBrand {
            get {
                return ResourceManager.GetString("NavBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forma.
        /// </summary>
        public static string NavForm {
            get {
                return ResourceManager.GetString("NavForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagrindinis.
        /// </summary>
        public static string NavHome {
            get {
                return ResourceManager.GetString("NavHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perjungti navigaciją.
        /// </summary>
        public static string NavToggle {
            get {
                return ResourceManager.GetString("NavToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto forma.
        /// </summary>
        public static string NavVehicleForm {
            get {
                return ResourceManager.GetString("NavVehicleForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nauja sutartis.
        /// </summary>
        public static string NewContract {
            get {
                return ResourceManager.GetString("NewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toliau.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nėra.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutarties sudarymo valstybė.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kitu metu.
        /// </summary>
        public static string OtherTime {
            get {
                return ResourceManager.GetString("OtherTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Papildoma informacija apie atsiskaitymo būdą ir (ar) kitas sąlygas:.
        /// </summary>
        public static string PaymentAdditionalInfo {
            get {
                return ResourceManager.GetString("PaymentAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsiskaitymo momentas.
        /// </summary>
        public static string PaymentDate {
            get {
                return ResourceManager.GetString("PaymentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mokėjimo duomenys.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsiskaitymo būdas.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite mokėjimo būdą.
        /// </summary>
        public static string PaymentMethodRequired {
            get {
                return ResourceManager.GetString("PaymentMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atsiskaitymo momentas.
        /// </summary>
        public static string PaymentMoment {
            get {
                return ResourceManager.GetString("PaymentMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bankiniu pavedimu.
        /// </summary>
        public static string PaymentType_BankTransfer {
            get {
                return ResourceManager.GetString("PaymentType_BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grynaisiais pinigais.
        /// </summary>
        public static string PaymentType_Cash {
            get {
                return ResourceManager.GetString("PaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telefono numeris.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono numeris turi sudaryti tik skaičiai.
        /// </summary>
        public static string PhoneDigitsOnly {
            get {
                return ResourceManager.GetString("PhoneDigitsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefono numeris yra privalomas.
        /// </summary>
        public static string PhoneRequired {
            get {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės kaina.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaina turi būti didesnė nei 0.
        /// </summary>
        public static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonė eismo ar kitų įvykių metu per laikotarpį, kurį buvau parduodamos transporto priemonės savininkas.
        /// </summary>
        public static string PriorDamageKnown {
            get {
                return ResourceManager.GetString("PriorDamageKnown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privatumo politika.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valstybinis registracijos numeris (A).
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registracijos numeris yra privalomas.
        /// </summary>
        public static string RegistrationNumberRequired {
            get {
                return ResourceManager.GetString("RegistrationNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės savininko deklaravimo kodas (SDK).
        /// </summary>
        public static string Sdk {
            get {
                return ResourceManager.GetString("Sdk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDK yra privalomas.
        /// </summary>
        public static string SdkRequired {
            get {
                return ResourceManager.GetString("SdkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Pasirinkite šalį --.
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės trūkumai.
        /// </summary>
        public static string SelectedDamages {
            get {
                return ResourceManager.GetString("SelectedDamages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardavėjo Duomenys.
        /// </summary>
        public static string SellerInformation {
            get {
                return ResourceManager.GetString("SellerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apžvalga.
        /// </summary>
        public static string SellerReview {
            get {
                return ResourceManager.GetString("SellerReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pardavėjo duomenys.
        /// </summary>
        public static string SellersInformation {
            get {
                return ResourceManager.GetString("SellersInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parduoti dabar.
        /// </summary>
        public static string SellNowButton {
            get {
                return ResourceManager.GetString("SellNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siųsti pranešimą pirkėjui.
        /// </summary>
        public static string SendNotificationToBuyer {
            get {
                return ResourceManager.GetString("SendNotificationToBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjas gaus el. laišką su nuoroda užpildyti informaciją ir pasirašyti sutartį..
        /// </summary>
        public static string SendNotificationToBuyerDescription {
            get {
                return ResourceManager.GetString("SendNotificationToBuyerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirašyti.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parašas.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parašas yra privalomas.
        /// </summary>
        public static string SignatureRequired {
            get {
                return ResourceManager.GetString("SignatureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirašyti šiame įrenginyje.
        /// </summary>
        public static string SignOnThisDevice {
            get {
                return ResourceManager.GetString("SignOnThisDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pirkėjas užpildys informaciją ir pasirašys sutartį šiame įrenginyje..
        /// </summary>
        public static string SignOnThisDeviceDescription {
            get {
                return ResourceManager.GetString("SignOnThisDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Žingsnis.
        /// </summary>
        public static string StepText {
            get {
                return ResourceManager.GetString("StepText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pateikti.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naudojimo sąlygos.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sutinku su &lt;a href=&quot;/terms-and-conditions&quot;&gt;naudojimo sąlygomis&lt;/a&gt; ir &lt;a href=&quot;/privacy-policy&quot;&gt;privatumo politika&lt;/a&gt;.
        /// </summary>
        public static string TermsAndConditionsConsent {
            get {
                return ResourceManager.GetString("TermsAndConditionsConsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perduoti draudimą pirkėjui.
        /// </summary>
        public static string TransferInsurance {
            get {
                return ResourceManager.GetString("TransferInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to galioja.
        /// </summary>
        public static string Valid {
            get {
                return ResourceManager.GetString("Valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacija apie įvykius ir trūkumus.
        /// </summary>
        public static string VehicleAdditionalInfo {
            get {
                return ResourceManager.GetString("VehicleAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporto priemonės duomenys.
        /// </summary>
        public static string VehicleInformation {
            get {
                return ResourceManager.GetString("VehicleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taip.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
